{"name": "test_login[standard_user-2452]", "status": "failed", "statusDetails": {"message": "AssertionError: Invalid credentials\nassert 'Epic sadface... this service' == ''\n  \n  + Epic sadface: Username and password do not match any user in this service", "trace": "username = 'standard_user', password = '2452'\n\n    @pytest.mark.login\n    @pytest.mark.parametrize(\"username, password\", get_data())\n    def test_login(username, password):\n        driver = SeleniumWebDriver(implicitly_wait=1, explicitly_wait=1)\n        page = SauceDemoPage(driver)\n        msg = page.Login(username, password)\n        allure.attach(driver.get_screenshot_as_png(), name='users', attachment_type=AttachmentType.PNG)\n        driver.close(exit_time=2)\n>       assert msg == '', 'Invalid credentials'\nE       AssertionError: Invalid credentials\nE       assert 'Epic sadface... this service' == ''\nE         \nE         + Epic sadface: Username and password do not match any user in this service\n\nreports\\test_03_pytest_allure_screenshot.py:28: AssertionError"}, "attachments": [{"name": "users", "source": "1c7c52bb-8820-4366-9799-857af710e74a-attachment.png", "type": "image/png"}], "parameters": [{"name": "username", "value": "'standard_user'"}, {"name": "password", "value": "'2452'"}], "start": 1707771558665, "stop": 1707771564316, "uuid": "2cd01b17-4de4-4cf5-af61-27e429d6067a", "historyId": "c39d0cfbb7d51362256c838a8c6c974e", "testCaseId": "b8114e60717ba55b71422ad5396fbcd5", "fullName": "reports.test_03_pytest_allure_screenshot#test_login", "labels": [{"name": "tag", "value": "login"}, {"name": "parentSuite", "value": "reports"}, {"name": "suite", "value": "test_03_pytest_allure_screenshot"}, {"name": "host", "value": "DESKTOP-551JSCE"}, {"name": "thread", "value": "51964-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "reports.test_03_pytest_allure_screenshot"}]}