{"name": "test_login[Gilberto-secret_sauce]", "status": "failed", "statusDetails": {"message": "AssertionError: Invalid credentials\nassert 'Epic sadface... this service' == ''\n  \n  + Epic sadface: Username and password do not match any user in this service", "trace": "username = 'Gilberto', password = 'secret_sauce'\n\n    @pytest.mark.login\n    @pytest.mark.parametrize(\"username, password\", get_data())\n    def test_login(username, password):\n        driver = SeleniumWebDriver(implicitly_wait=1, explicitly_wait=1)\n        page = SauceDemoPage(driver)\n        msg = page.Login(username, password)\n        allure.attach(driver.get_screenshot_as_png(), name='users', attachment_type=AttachmentType.PNG)\n        driver.close(exit_time=2)\n>       assert msg == '', 'Invalid credentials'\nE       AssertionError: Invalid credentials\nE       assert 'Epic sadface... this service' == ''\nE         \nE         + Epic sadface: Username and password do not match any user in this service\n\nreports\\test_03_pytest_allure_screenshot.py:28: AssertionError"}, "attachments": [{"name": "users", "source": "6147f5fb-fcf0-4996-b350-317cfe9b06e6-attachment.png", "type": "image/png"}], "parameters": [{"name": "username", "value": "'Gilberto'"}, {"name": "password", "value": "'secret_sauce'"}], "start": 1707771564345, "stop": 1707771574221, "uuid": "f61053f3-0593-4111-8ca3-145023f9f763", "historyId": "bc65430f948ea3a99eb693555f634bb8", "testCaseId": "b8114e60717ba55b71422ad5396fbcd5", "fullName": "reports.test_03_pytest_allure_screenshot#test_login", "labels": [{"name": "tag", "value": "login"}, {"name": "parentSuite", "value": "reports"}, {"name": "suite", "value": "test_03_pytest_allure_screenshot"}, {"name": "host", "value": "DESKTOP-551JSCE"}, {"name": "thread", "value": "51964-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "reports.test_03_pytest_allure_screenshot"}]}