{"name": "test_login[Padro-asdf]", "status": "failed", "statusDetails": {"message": "AssertionError: Invalid credentials\nassert 'Epic sadface... this service' == ''\n  \n  + Epic sadface: Username and password do not match any user in this service", "trace": "username = 'Padro', password = 'asdf'\n\n    @pytest.mark.login\n    @pytest.mark.usefixtures('log_on_failure')\n    @pytest.mark.parametrize(\"username, password\", get_data())\n    def test_login(username, password):\n        global driver, page\n        msg = page.Login(username, password)\n        allure.attach(driver.get_screenshot_as_png(), name=\"Login\", attachment_type=AttachmentType.PNG)\n>       assert msg == '', 'Invalid credentials'\nE       AssertionError: Invalid credentials\nE       assert 'Epic sadface... this service' == ''\nE         \nE         + Epic sadface: Username and password do not match any user in this service\n\nreports\\test_04_pytest_allure_screenshot_error.py:44: AssertionError"}, "attachments": [{"name": "Login", "source": "af2e905c-5501-42e8-b964-14fbe1402ebc-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "e0cd7e2f-965e-4c9c-ac62-87afb1b53581-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'Padro'"}, {"name": "password", "value": "'asdf'"}], "start": 1707773449507, "stop": 1707773450561, "uuid": "b564ec38-5a9a-4468-ad51-a3ee1580f98b", "historyId": "4e2d810b37df6f8db5ac58122232b20e", "testCaseId": "d3da2953cdfd9c49173b93a1b4e4916c", "fullName": "reports.test_04_pytest_allure_screenshot_error#test_login", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('log_on_failure')"}, {"name": "tag", "value": "login"}, {"name": "parentSuite", "value": "reports"}, {"name": "suite", "value": "test_04_pytest_allure_screenshot_error"}, {"name": "host", "value": "DESKTOP-551JSCE"}, {"name": "thread", "value": "72136-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "reports.test_04_pytest_allure_screenshot_error"}]}