{"name": "test_login[Gilberto-secret_sauce]", "status": "failed", "statusDetails": {"message": "AssertionError: Invalid credentials\nassert 'Epic sadface... this service' == ''\n  \n  + Epic sadface: Username and password do not match any user in this service", "trace": "username = 'Gilberto', password = 'secret_sauce'\n\n    @pytest.mark.login\n    @pytest.mark.usefixtures('log_on_failure')\n    @pytest.mark.parametrize(\"username, password\", get_data())\n    def test_login(username, password):\n        global driver, page\n        msg = page.Login(username, password)\n        allure.attach(driver.get_screenshot_as_png(), name=\"Login\", attachment_type=AttachmentType.PNG)\n>       assert msg == '', 'Invalid credentials'\nE       AssertionError: Invalid credentials\nE       assert 'Epic sadface... this service' == ''\nE         \nE         + Epic sadface: Username and password do not match any user in this service\n\nreports\\test_04_pytest_allure_screenshot_error.py:44: AssertionError"}, "attachments": [{"name": "Login", "source": "f941f3b2-f364-4008-939a-56845e1be472-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "f091edee-9e11-493d-b6ee-38aaa0f8862a-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'Gilberto'"}, {"name": "password", "value": "'secret_sauce'"}], "start": 1707773473350, "stop": 1707773474388, "uuid": "953db473-1ccb-49fe-838f-f01ac5819de6", "historyId": "136f16a971aa7e78bc26b4e671654a9e", "testCaseId": "d3da2953cdfd9c49173b93a1b4e4916c", "fullName": "reports.test_04_pytest_allure_screenshot_error#test_login", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('log_on_failure')"}, {"name": "tag", "value": "login"}, {"name": "parentSuite", "value": "reports"}, {"name": "suite", "value": "test_04_pytest_allure_screenshot_error"}, {"name": "host", "value": "DESKTOP-551JSCE"}, {"name": "thread", "value": "72136-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "reports.test_04_pytest_allure_screenshot_error"}]}