{"name": "test_login[Karina-2452]", "status": "failed", "statusDetails": {"message": "AssertionError: Invalid credentials\nassert 'Epic sadface... this service' == ''\n  \n  + Epic sadface: Username and password do not match any user in this service", "trace": "username = 'Karina', password = '2452'\n\n    @pytest.mark.login\n    @pytest.mark.usefixtures('log_on_failure')\n    @pytest.mark.parametrize(\"username, password\", get_data())\n    def test_login(username, password):\n        global driver, page\n        msg = page.Login(username, password)\n        allure.attach(driver.get_screenshot_as_png(), name=\"Login\", attachment_type=AttachmentType.PNG)\n>       assert msg == '', 'Invalid credentials'\nE       AssertionError: Invalid credentials\nE       assert 'Epic sadface... this service' == ''\nE         \nE         + Epic sadface: Username and password do not match any user in this service\n\nreports\\test_04_pytest_allure_screenshot_error.py:44: AssertionError"}, "attachments": [{"name": "Login", "source": "8a69d8ca-b198-4504-819b-70d7d7a655c9-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "4b76051d-2523-44b8-808c-2e0f687cf2f8-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'Karina'"}, {"name": "password", "value": "'2452'"}], "start": 1707773457409, "stop": 1707773458481, "uuid": "744d9668-4ba3-4004-8a21-30bf99de769e", "historyId": "0c5cb3d8b7df9160d2c86e9d27de7b0d", "testCaseId": "d3da2953cdfd9c49173b93a1b4e4916c", "fullName": "reports.test_04_pytest_allure_screenshot_error#test_login", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('log_on_failure')"}, {"name": "tag", "value": "login"}, {"name": "parentSuite", "value": "reports"}, {"name": "suite", "value": "test_04_pytest_allure_screenshot_error"}, {"name": "host", "value": "DESKTOP-551JSCE"}, {"name": "thread", "value": "72136-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "reports.test_04_pytest_allure_screenshot_error"}]}